### ISSUE TITLE
TypeError: Cannot read property 'findNode' of undefined

### ISSUE THREAD

**Issue by havardl** [noxify/gridsome-plugin-remote-image#10]
First off, thanks for creating this plugin, the lack of this support has been one of the biggest issues with implementing Gridsome with new projects. 

After installing the plugin and adding it in the config, I'm currently getting the following error when running `gridsome develop` (v 0.7.13):

```
TypeError: Cannot read property 'findNode' of undefined
    at ImageDownloader.getFieldType (\node_modules\@noxify\gridsome-plugin-remote-image\gridsome.server.js:138:37)
    at ImageDownloader.api.loadSource (\node_modules\@noxify\gridsome-plugin-remote-image\gridsome.server.js:32:36)
    at Plugins.run (\node_modules\gridsome\lib\app\Plugins.js:141:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'm using Strapi as my data source, but I'm not sure if I understand the naming convention correctly. Shouldn't typeName be my collection (Strapi) and the sourceField where the image url is located?

```javascript
  plugins: [
    {
      use: "gridsome-source-strapi",
      options: {
        contentTypes: [
          "teams"
        ]
      }
    },
    {
      use: "@noxify/gridsome-plugin-remote-image",
      options: {
        typeName: "Strapi",
        sourceField: "teams.edges.node.fields.photo_250x250.url",
        targetField: "imageDownloaded",
        targetPath: "./src/assets/remoteImages"
      }
    }
```

**Comment by noxify** [comment]
Hi @havardl,

thanks for reporting.

It seems, that the current implementation via `api.loadSource` is not the best one,
because loading the data from a remote source needs some time.

Since the `loadSource` methods is called via `Promise` ( if I'm not wrong ), they're run in parallel.

Currently we have no solution for this, sorry.

**Comment by travis-r6s** [comment]
@noxify The most recent release of Gridsome (v0.7.15) adds support for a promise-style `onBootstrap` hook, which may be better for this sort of operation. It also runs _after_ `loadSource` and `onCreateNode`, so the internal store will have all the data needed.

**Comment by noxify** [comment]
Thanks for the hint :) did they released a new version (0.7.15)?

**Comment by travis-r6s** [comment]
https://www.npmjs.com/package/gridsome/v/0.7.15

**Comment by noxify** [comment]
@thetre97 thanks for the link - i have blocked some time today to test it :)

**Comment by noxify** [comment]
Hey @thetre97,

i tried to get it running with `onBootstrap` but it seems I'm too stupid for this...

## What is working

#### Running a  `console.log` via `api.onBootstrap` prints the log at the expected place

Example:
```
Initializing plugins...
Load sources - 0.33s
Create GraphQL schema - 0.05s
Create pages and templates - 0.05s
Generate temporary code - 0.06s
### Console log via onBootstrap
```

#### Calling the GraphQL to check if the defined field exists in the collection

To test this behavior ( or the bug? ), I use Contenful as data source.
My initial test failed with the described error message in the initial post from @havardl .

With the `onBootstrap` "implementation", everything works as expected for this step.

## What is not working

#### Creating a new Schema Type <-- Here I need some help

Since we're in the "hook" logic, it's not possible to run a command which extends the GraphQL. 

Please find below my steps to reproduce.

## Not tested

#### Updating the nodes

Since I wasn't able to add a new schema type to the GraphQL, i didn't invest some time to check this.

----

## Steps to reproduce

To test it locally:

1. Create a new gridsome page via `gridsome create remote_downloader`
2. Install and configure a source plugin and if needed, also the remark-transformer plugin
3. Run `cd remote_downloader` to change the directory
4. Create a new directory with the name `packages`
5. Run `cd packages`
6. Run `git clone https://github.com/noxify/gridsome-plugin-remote-image imageDownloader`
7. Run `cd imageDownloader`
8. Run `npm install`

After this 8 steps you have to overwrite the `packages/imageDownloader/gridsome.server.js` with the following content: https://gist.github.com/noxify/7f3085b400991535ef997dedaacf2b1d

> **Note:** The code from the gist includes only the parts which are needed to show what's not working - it doesn't download an image or something else!

In the `/gridsome.config.js` you have to define the plugin like this:
```
 {
      use: '~/packages/imageDownloader',
      options: {
        'typeName' : 'ContentfulAsset',
        'sourceField': 'file.url',
        'targetField': 'imageDownloaded',
        'targetPath': './src/assets/remoteImages'
      }
 }
```

With the code from the gist, it doesn't matter which source plugin you're using.

**Comment by travis-r6s** [comment]
@noxify Ah yes, that's true - I hadn't thought about that.

I guess in theory you would need to have multiple stages:

1. Gridsome already includes an `Image` schema type, so shouldn't be any need to add that.
2. Use `onCreateNode` to check if a node matches the target typeName, if so edit it to add an `Image` relation under another field (i.e. `localImage`, and 'optimistically' add the local image path, assuming it the filename will be the same as the remote url filename. E.g. `{ file: { url: 'https://example.com/image.jpg', localImage: { type: 'Image', path: './src/assets/remoteImages/image.jpg''} } }` (psuedo code)
3. When it gets to `onBootstrap`, get the target field type, loop through it and download & save using the target url & local path.

Don't know whether that actually makes it more complicated though 🤔😏I'm also assuming that `onBootstrap` runs before the asset processing queue.

**Comment by noxify** [comment]
Hi @thetre97 

thanks for the fast feedback.

> Gridsome already includes an Image schema type, so shouldn't be any need to add that.

The new field type is needed in case, that if the source field is an array, the target field has to be an array, too.

Since it seems not possible to use `[Image]` directly in the target field definition, I use `addSchemaType` to create a new type `Images`, which has `image: [Image]` as definition.

> Use onCreateNode to check if a node matches the target typeName, if so edit it to add an Image relation under another field...

This could work - I have to verify it.

> When it gets to onBootstrap, get the target field type, loop through it and download & save using the target url & local path.

Maybe we should download the remote images inside `onCreateNode` - Because if the download wasn't successful, we should set the value from the target field to `null`.

> Don't know whether that actually makes it more complicated though

Maybe :)  but if it's working with remote source we can generate a benefit for the community.
Refactoring it later should not be the problem. If I'm not wrong, there are some plans to extend the hook system in the next gridsome versions.

**Comment by noxify** [comment]
here the result from my first tests with `api.onCreateNode()` and `api.createSchema()`.

```
Initializing plugins...
### Run Create Node
### Run Create Node
### Run Create Node
### Run Create Node
### Run Create Node
### Run Create Node
Load sources - 0.31s
### Run Create Schema
Create GraphQL schema - 0.05s
```

I hope i can continue this week.

**Comment by noxify** [comment]
Hey @thetre97 

i think I got it.

With the following code ( https://gist.github.com/noxify/7f3085b400991535ef997dedaacf2b1d ), it seems to work as expected.

Next steps are to activate the image downloader.

Thanks a lot for all the hints <3 

What is currently working:
* Adding the new schema type `Images`
* Adding the defined target field to the collection schema
* Updating the collection nodes
* GraphQL converts the path to a valid image

**Comment by noxify** [comment]
Hey @dsturm @havardl @thetre97

I have created a new branch with all changes:

https://github.com/noxify/gridsome-plugin-remote-image/tree/fix/findNodes

Please feel free to test and check that everything is working.
My test with the contenful source was successful, but to make sure there is no hidden breaking change, it would be good if someone else could test it, too.

**Comment by travis-r6s** [comment]
Great - nice work. I'll give it a try this w/e...

**Comment by noxify** [comment]
fixed with https://github.com/noxify/gridsome-plugin-remote-image/releases/tag/v1.1.0

**Comment by rogoit** [comment]
Is not fixed for me ;) https://github.com/nevercodealone/strapi-rolandgolla.de/pull/new/feature/remoteImage
Faild on gridsome develop

**Comment by noxify** [comment]
Hey @rogoit 

it seems there is no source defined in your https://github.com/nevercodealone/strapi-rolandgolla.de/blob/feature/remoteImage/gridsome/gridsome.config.js

**Comment by rogoit** [comment]
Maybe I can fix the docs with your next answer ;) https://webstone.info/documentation/gridsome-plugin-remote-image/

**Comment by rogoit** [comment]
I do not find anywhere an example for the right configuration...do you have a link? @noxify

**Comment by noxify** [comment]
What exactly is your problem?

The main problem yesterday was that there was no source plugin defined. 

Did you add a source plugin to your project and configured it correctly in your `gridsome.config.js`?

**Comment by rogoit** [comment]
Hi, maybe i am not the best on JS. But i installed the plugin and add the setting to my config as you see in the link. You tell me something from a source. But I did not find any example of a property source.

So i sent you my example code. But I do not know what I have to do now. Thx for your answer and passion by the way ;)

**Comment by rogoit** [comment]
Add the error comes up with installation and setting. The error from the topic here. On actual master everything is fine

**Comment by noxify** [comment]
@rogoit - ping mich am besten per Discord mal an :)

User ID: Marcus from JammeryHQ#3715
